"use client";

import { stakingSupplyHistoryQuery } from "@/queries/options";
import { formatCurrencyNumber } from "@/utils/number";
import { useQuery } from "@tanstack/react-query";
import type { ComponentProps } from "react";
import { GenericCard } from "./generic-card";

const startOfYear = new Date(new Date().getFullYear(), 0, 1); // January 1st of current year
const today = new Date();

export function TotalFeesCard({ ...rest }: ComponentProps<"div">) {
  const { data } = useQuery({
    ...stakingSupplyHistoryQuery(startOfYear, today),
    select(data) {
      return formatCurrencyNumber(
        data.map((el) => el.buybackFee).reduce((p, c) => p + c, 0),
      );
    },
  });

  return (
    <GenericCard
      title="Total Protocol Fees Generated"
      description="Total fees generated by the dYdX protocol."
      {...rest}
    >
      <div className="flex flex-col items-center gap-1">
        <h3 className="text-foreground text-7xl font-bold">{data}</h3>
        <p className="text-primary text-xs">USD</p>
      </div>
    </GenericCard>
  );
}
