"use client";

import { stakingSupplyHistoryQuery } from "@/queries/options";
import { formatCurrencyNumber } from "@/utils/number";
import { useQuery } from "@tanstack/react-query";
import type { ComponentProps } from "react";
import { Filters, useFilters } from "./filters";
import { GenericCard } from "./generic-card";

export function TotalFeesCard({ ...rest }: ComponentProps<"div">) {
  const { filter, filters, setFilter } = useFilters();

  const { data } = useQuery({
    ...stakingSupplyHistoryQuery(filters.start, filters.end),
    select(data) {
      return formatCurrencyNumber(
        data.map((el) => el.protocolRevenue).reduce((p, c) => p + c, 0),
      );
    },
  });

  return (
    <GenericCard
      title="Total Protocol Fees Generated"
      description="Total fees generated by the dYdX protocol."
      actions={<Filters value={filter} onValueChange={setFilter} />}
      {...rest}
    >
      <div className="flex flex-col items-center gap-1">
        <h3 className="text-foreground text-7xl font-bold">{data}</h3>
        <p className="text-primary text-xs">USD</p>
      </div>
    </GenericCard>
  );
}
